### ISSUE TITLE
Inconstency in Password change

### ISSUE THREAD

**Issue by TiJac** [Baqend/guide#1]
The Video Tutorial asks me to change the password in the AppData/User view.
Inside this view it is not possible to submit a password hange, although the user is able to enter a new password. (maybe because the old one is not entered and submitted)
The failure message in such an attempt does not lead to the following solution:
The user needs to enter the submenu of the account information to get a formula for password change.

**Comment by mlauenroth** [comment]
Hi TiJac,
thank you for pointing that out. We will make sure to update the video shortly. We secretly updated the package last month. - unofficially.
The official announcement and another update with all of the scheduled futures is going to be there soon. Probably within this month.
Gonna be exciting!

**Comment by mlauenroth** [comment]
Hi TiJac,
Baqend has seen major changes in the course of this year. We have made a few updates to the package, but did not update the video since the initial launch in April. Most of the people testing Baqend had direct contact with us and we did not jet publish on a broader public channel. So the priorities had been elsewhere. But the video will be updated in the next few weeks.

Thank you for testing and sorry for the inconvenience.
Best regards
Malte
